Repository cbnu-buddy/buddy-server, pull requests merged in 2024-08, with the labels that each got.

#80 [feat] 댓글 작성/수정/삭제 기능 추가
  src/main/java/com/example/controller/community/CommentController.java
  src/main/java/com/example/domain/community/Comment.java
  src/main/java/com/example/dto/request/CommentRequest.java
  src/main/java/com/example/exception/ErrorCode.java
  src/main/java/com/example/repository/community/CommentRepository.java
  src/main/java/com/example/service/community/CommentService.java
Labels: feat

#86 [fix] README.md 파일 수정 #85
  README.md
Labels: fix

#88 [fix] README.md 파일 수정 2 #87
  README.md
Labels: fix

#90 [feat] '내가 쓴 커뮤니티 게시글 목록 조회' 기능에 댓글 수 추가 #89
  src/main/java/com/example/domain/community/Post.java
  src/main/java/com/example/dto/response/MyPostResponse.java
  src/main/java/com/example/repository/community/CommentRepository.java
  src/main/java/com/example/repository/community/ReplyRepository.java
  src/main/java/com/example/service/community/CommunityService.java
Labels: feat

#96 [fix] API 엔드포인트 및 응답 바디 수정 #95
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/controller/party/PartyController.java
  src/main/java/com/example/controller/subscribe/SubscribeController.java
  src/main/java/com/example/dto/response/TagSubInfoResponse.java
  src/main/java/com/example/repository/community/PostRepository.java
  src/main/java/com/example/service/subscribe/SubscribeService.java
Labels: fix

#101 [feat] 파일 업로드 기능 추가 #100
  build.gradle
  src/main/java/com/example/controller/upload/UploadController.java
  src/main/java/com/example/repository/community/PostTagRepository.java
  src/main/java/com/example/service/upload/UploadService.java
  src/main/resources/application.yml
Labels: feat

#103 [feat] 태그 기반 커뮤니티 게시글 목록 정보 조회 기능 추가 #97
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/dto/response/PostsByTagInfoResponse.java
  src/main/java/com/example/repository/community/CommentRepository.java
  src/main/java/com/example/repository/community/PostRepository.java
  src/main/java/com/example/repository/community/PostTagRepository.java
  src/main/java/com/example/repository/community/ReplyRepository.java
  src/main/java/com/example/service/community/CommunityService.java
Labels: feat

#105 [feat] 커뮤니티 게시글 정보 조회 API 추가 #104
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/dto/response/CommunityPostResponse.java
  src/main/java/com/example/service/community/CommunityService.java
Labels: feat

#107 [feat] 최신 커뮤니티 게시글 목록 조회 API 추가 #106
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/dto/response/CommunityPostResponse.java
  src/main/java/com/example/service/community/CommunityService.java
Labels: feat

#110 [feat] 댓글 좋아요/취소 API 추가 #109
  src/main/java/com/example/controller/community/CommentController.java
  src/main/java/com/example/domain/community/CommentLike.java
  src/main/java/com/example/domain/community/CommentLikeId.java
  src/main/java/com/example/exception/ErrorCode.java
  src/main/java/com/example/repository/community/CommentLikeRepository.java
  src/main/java/com/example/service/community/CommentService.java
Labels: feat

#112 [feat] 답글 좋아요/취소 API 추가 #109-111
  src/main/java/com/example/controller/community/ReplyController.java
  src/main/java/com/example/domain/community/ReplyLike.java
  src/main/java/com/example/domain/community/ReplyLikeId.java
  src/main/java/com/example/exception/ErrorCode.java
  src/main/java/com/example/repository/community/ReplyLikeRepository.java
  src/main/java/com/example/service/community/ReplyService.java
Labels: feat

#115 [fix] 기존 {post_like} 테이블명의 복수형으로 수정 및 {좋아요 취소하기} API 관련 400 에러 반환 코드의 404 에러가 반환되도록 수정 #114
  src/main/java/com/example/controller/community/PostLikeController.java
  src/main/java/com/example/domain/community/ReplyLike.java
  src/main/java/com/example/exception/ErrorCode.java
  src/main/java/com/example/service/community/PostLikeService.java
  src/main/java/com/example/service/community/ReplyService.java
Labels: fix

#117 [feat] 게시글 검색 정보 조회 / 태그 관련 통합 검색 정보 조회기능 추가 #113-108
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/domain/community/Post.java
  src/main/java/com/example/dto/response/MyPostResponse.java
  src/main/java/com/example/dto/response/PostsByTagInfoResponse.java
  src/main/java/com/example/dto/response/SearchResponse.java
  src/main/java/com/example/dto/response/SearchTagsResponse.java
  src/main/java/com/example/exception/ErrorCode.java
  src/main/java/com/example/repository/community/CommentLikeRepository.java
  src/main/java/com/example/repository/community/PostRepository.java
  src/main/java/com/example/repository/community/PostTagRepository.java
  src/main/java/com/example/repository/community/ReplyLikeRepository.java
  src/main/java/com/example/service/community/CommunityService.java
Labels: feat

#119 [feat] 인기 커뮤니티 게시글 목록 정보 조회 기능 추가 / 조회수 증가 로직 추가
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/repository/community/PostRepository.java
  src/main/java/com/example/service/community/CommunityService.java
Labels: feat

#121 [fix] 파일 업로드 관련 코드 수정 및 에러 반환 코드 추가 #120
  src/main/java/com/example/controller/community/CommunityController.java
  src/main/java/com/example/dto/response/MemberInfoResponse.java
  src/main/java/com/example/dto/response/PostsByTagInfoResponse.java
  src/main/java/com/example/exception/ErrorCode.java
  src/main/java/com/example/service/community/CommunityService.java
  src/main/java/com/example/service/member/MemberService.java
  src/main/java/com/example/service/upload/UploadService.java
Labels: fix

#123 [fix] 파티 매칭 완료시 이메일 전송 서비스 로직 수정 및 기능 개선 #122
  src/main/java/com/example/BuddyApplication.java
  src/main/java/com/example/config/async/AsyncConfig.java
  src/main/java/com/example/service/email/EmailService.java
Labels: fix

#125 [fix] 커뮤니티 게시글 생성하기 응답 바디 수정 #124
  src/main/java/com/example/service/community/CommunityService.java
Labels: fix

#127 [bug] 특정 플랜 내 매칭이 완료되지 않은 파티 목록 정보 조회 API 응답 에러 #126
  src/main/java/com/example/service/party/PartyService.java
Labels: bug

#131 [bug] 현재 매칭 대기 중인 모든 파티의 파티원 총 인원수 합산 값 조회 API 응답 에러 #130
  src/main/java/com/example/controller/party/PartyController.java
  src/main/java/com/example/repository/party/PartyRepository.java
  src/main/java/com/example/service/party/PartyService.java
Labels: bug
